on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Prepare Laravel App
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate
      - name: Run tests
        run: php artisan test
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Generate deployment packages
        run: |
          apt-get install -y zip
          zip -r deploy.zip . -x "vendor/*" "node_modules/*" "*.git*"
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          existing_bucket_name: ${{ secrets.AWS_BUCKET }}
          application_name: transparencia-atos-juridicos-api
          environment_name: Transparenciaatosjuridicosapi-env
          version_label: v1.0.0
          region: us-east-1
